In [2]:
import numpy as np

In [3]:
a=np.array([10,20,30,40,50])

a,type(a)

(array([10, 20, 30, 40, 50]), numpy.ndarray)

In [4]:
b=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [5]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [6]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [7]:
np.full([3,4],7)

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [8]:
arr=[[1,2,3,4],[5,6,7,8],[9,10,11,12]]


In [9]:
x=np.array(arr)

In [10]:
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [11]:
x=np.array([1,2,3])
x

array([1, 2, 3])

In [12]:
y=np.array((1,2,3))
y

array([1, 2, 3])

In [13]:
x=np.array(((1,2,3),(4,5,6),(7,8,9)))
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
x=np.zeros([3,4])
x

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
x.shape,x.size,x.ndim,x.itemsize,x.dtype

((3, 4), 12, 2, 8, dtype('float64'))

In [16]:
arr=np.zeros([2,3,4])

In [17]:
arr.ndim

3

In [18]:
arr.size

24

In [19]:
arr.shape

(2, 3, 4)

In [20]:
arr.dtype

dtype('float64')

In [21]:
b=np.zeros([2,3,4])

In [22]:
b.astype(np.int32)

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]], dtype=int32)

In [23]:
b.itemsize

8

In [24]:
x=np.zeros([5,6])

In [25]:
x

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [26]:
x.shape,x.ndim,x.size

((5, 6), 2, 30)

In [27]:
a=np.arange(1,11,1)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [28]:
a[0],a[-1],a[2],a[-2]

(np.int64(1), np.int64(10), np.int64(3), np.int64(9))

In [29]:
x=np.arange(1,26,1).reshape(5,5)

x

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [30]:
x[0][:]

array([1, 2, 3, 4, 5])

In [31]:
x[-1][:]

array([21, 22, 23, 24, 25])

In [32]:
x[:,0],x[:,-1]

(array([ 1,  6, 11, 16, 21]), array([ 5, 10, 15, 20, 25]))

In [33]:
x[0:3:1,0:3:1]

array([[ 1,  2,  3],
       [ 6,  7,  8],
       [11, 12, 13]])

In [34]:
x[-1:-3:-1,:]

array([[21, 22, 23, 24, 25],
       [16, 17, 18, 19, 20]])

In [35]:
x[:,1:4]

array([[ 2,  3,  4],
       [ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19],
       [22, 23, 24]])

In [36]:
x[:,::2]

array([[ 1,  3,  5],
       [ 6,  8, 10],
       [11, 13, 15],
       [16, 18, 20],
       [21, 23, 25]])

In [37]:
y=np.arange(1,37).reshape(6,6)

In [38]:
y

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [39]:
top=y[0,:]
bottom=y[-1,:]
left=y[:,0]
right=y[:,-1]

border=np.concatenate([left,right,top,bottom])
border


array([ 1,  7, 13, 19, 25, 31,  6, 12, 18, 24, 30, 36,  1,  2,  3,  4,  5,
        6, 31, 32, 33, 34, 35, 36])

In [40]:
np.diag(y)

array([ 1,  8, 15, 22, 29, 36])

In [41]:
z=np.eye(10)
z

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [42]:
np.arange(10,51,5)

array([10, 15, 20, 25, 30, 35, 40, 45, 50])

In [43]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [44]:
np.eye(5).astype(np.int64)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [45]:
np.eye(4).astype(np.int64)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [46]:
np.diag([10,20,30])

array([[10,  0,  0],
       [ 0, 20,  0],
       [ 0,  0, 30]])

In [47]:
np.linspace(-10,10,100)

array([-10.        ,  -9.7979798 ,  -9.5959596 ,  -9.39393939,
        -9.19191919,  -8.98989899,  -8.78787879,  -8.58585859,
        -8.38383838,  -8.18181818,  -7.97979798,  -7.77777778,
        -7.57575758,  -7.37373737,  -7.17171717,  -6.96969697,
        -6.76767677,  -6.56565657,  -6.36363636,  -6.16161616,
        -5.95959596,  -5.75757576,  -5.55555556,  -5.35353535,
        -5.15151515,  -4.94949495,  -4.74747475,  -4.54545455,
        -4.34343434,  -4.14141414,  -3.93939394,  -3.73737374,
        -3.53535354,  -3.33333333,  -3.13131313,  -2.92929293,
        -2.72727273,  -2.52525253,  -2.32323232,  -2.12121212,
        -1.91919192,  -1.71717172,  -1.51515152,  -1.31313131,
        -1.11111111,  -0.90909091,  -0.70707071,  -0.50505051,
        -0.3030303 ,  -0.1010101 ,   0.1010101 ,   0.3030303 ,
         0.50505051,   0.70707071,   0.90909091,   1.11111111,
         1.31313131,   1.51515152,   1.71717172,   1.91919192,
         2.12121212,   2.32323232,   2.52525253,   2.72

In [50]:
x=np.arange(1,13).reshape([3,4])
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [51]:
x=np.arange(1,25)

In [53]:
x.reshape([2,12])

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [54]:
x.reshape(3,8)

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24]])

In [55]:
x.reshape(4,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [56]:
x.reshape([2,3,4])

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [58]:
x= np.arange(1,13).reshape(3,4)

In [59]:
x.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [60]:
x.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [61]:
a=np.arange(1,11)

In [62]:
np.sum(a),np.mean(a),np.median(a),np.max(a),np.min(a)

(np.int64(55), np.float64(5.5), np.float64(5.5), np.int64(10), np.int64(1))

In [63]:
np.arange(1,11).sum()

np.int64(55)

In [64]:
per=np.array([1,2,3,4,5])

In [65]:
arr = np.array([10, 20, 50, 20])

# Calculate the sum of all elements
total = np.sum(arr)

# Calculate the percentage contribution of each element
percentages = (arr / total) * 100

print("Original array:", arr)
print("Percentage contribution:", percentages)

Original array: [10 20 50 20]
Percentage contribution: [10. 20. 50. 20.]


In [69]:
x=np.arange(1,13).reshape(3,4)
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [70]:
x.sum(axis=1)

array([10, 26, 42])

In [72]:
x.sum(axis=0)

array([15, 18, 21, 24])

In [73]:
x.argmax()

np.int64(11)

In [77]:
x=np.arange(1,5)

print(x[x>2])

[3 4]


In [79]:
x=np.arange(1,21)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [80]:
print(x[x%2==0])

[ 2  4  6  8 10 12 14 16 18 20]


In [86]:
b=np.linspace(10,140,14).astype(np.int64)
b


array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120, 130,
       140])

In [87]:
print(b[b>80])

[ 90 100 110 120 130 140]


In [88]:
print(b[(b>50) & (b<80)])

[60 70]


In [89]:
print(b[b<50])

[10 20 30 40]


In [90]:
sal=np.linspace(10000,50000,13).astype(np.int64)

In [91]:
sal

array([10000, 13333, 16666, 20000, 23333, 26666, 30000, 33333, 36666,
       40000, 43333, 46666, 50000])

In [93]:
output=sal[sal<30000]

In [94]:
print(output+output*0.10)

[11000.  14666.3 18332.6 22000.  25666.3 29332.6]


In [96]:
given=np.linspace(-10,10,10)
given

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [98]:
given=np.where(given<0,0,given)

In [99]:
given

array([ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        1.11111111,  3.33333333,  5.55555556,  7.77777778, 10.        ])

In [102]:
given=np.linspace(90,140,10).astype(np.int64)
given

array([ 90,  95, 101, 106, 112, 117, 123, 128, 134, 140])

In [103]:
given=np.where(given>100,100,given)

In [104]:
given

array([ 90,  95, 100, 100, 100, 100, 100, 100, 100, 100])

In [105]:
given=np.linspace(10000,100000,15).astype(np.int64)

In [106]:
given

array([ 10000,  16428,  22857,  29285,  35714,  42142,  48571,  55000,
        61428,  67857,  74285,  80714,  87142,  93571, 100000])

In [108]:
sal=given[given>50000]
sal

array([ 55000,  61428,  67857,  74285,  80714,  87142,  93571, 100000])

In [109]:
np.random.randint(1,100,10)

array([42, 61, 93, 33, 22, 82, 36,  6,  8, 47], dtype=int32)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()