In [1]:
import numpy as np

In [ ]:
# np.__version__

'2.4.6'

In [ ]:
# l=[1,2,3,4,5]
# l

[1, 2, 3, 4, 5]

In [ ]:
# type(l)

list

In [ ]:
# a=np.array(l)

In [ ]:
# type(a)

numpy.ndarray

In [ ]:
# a

array([1, 2, 3, 4, 5])

In [ ]:
# l=(1,)

In [ ]:
# type(l)

tuple

In [ ]:
# a=np.array(l)

In [ ]:
# type(a)

numpy.ndarray

In [ ]:
# np.zeros((2))

array([0., 0.])

In [ ]:
# np.ones((1))

array([1.])

In [ ]:
# b=np.full(3,[2,3,4])

In [ ]:
# type(b)

numpy.ndarray

In [ ]:
# c=[[22,3,4,5],[22,3,4,5]]

In [ ]:
# d=np.array(c)

In [ ]:
# np.shape(d)

(2, 4)

In [ ]:
# np.size(d)

8

In [ ]:
# np.ndim(d)

2

In [ ]:
# print(d.dtype)

int64


In [ ]:
# print(d.itemsize)

8


In [ ]:
# np.full((3,4),5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [ ]:
a=[True,False,,False]
x=np.array(a)

In [70]:
print(type(x[1]))

<class 'numpy.str_'>


In [71]:
a=[[1,2,3],[4,5,6]]

In [73]:
b=np.array(a)

In [75]:
b.ndim

2

In [81]:
arr=np.array([[1,2,3],[4,5,6]])

In [120]:
print(arr[1][0])

4


In [121]:
print(arr[0][0:2:])

[1 2]


In [123]:
print(arr[1][-1:-3:-1])

[6 5]


In [124]:
arr[0]

array([1, 2, 3])

In [136]:
x=np.arange(1,13,1)

In [137]:
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [142]:
x=np.linspace(1,5,12)

In [139]:
x

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [140]:
x.ndim

1

In [143]:
x.reshape(2,3,2)

array([[[1.        , 1.36363636],
        [1.72727273, 2.09090909],
        [2.45454545, 2.81818182]],

       [[3.18181818, 3.54545455],
        [3.90909091, 4.27272727],
        [4.63636364, 5.        ]]])

In [6]:
d=np.arange(1,13,1)

In [7]:
arr=np.array(d)

In [11]:
x=arr.reshape(2,2,3)

In [9]:
x

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [16]:
x[0][:,0]

array([1, 4])

In [2]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [1, 2, 3],
    [7, 8, 9],
    [4, 5, 6]
])

In [3]:
arr


array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [7, 8, 9],
       [4, 5, 6]])

In [4]:
unique_elements = np.unique(arr,axis=0)

In [11]:
unique_elements

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
np.unique_counts(arr)
    

UniqueCountsResult(values=array([0, 1, 2]), counts=array([6, 6, 3]))

In [13]:
dict

{(np.int64(0), np.int64(0), np.int64(0)): 0,
 (np.int64(1), np.int64(1), np.int64(1)): 0,
 (np.int64(2), np.int64(2), np.int64(2)): 0}

In [5]:
arr = np.array([10, 20, 5, 20, 30, 40, 40, 15])

In [10]:
x=np.unique_counts(arr)

In [11]:
x[1][0],x[0][0]

(np.int64(1), np.int64(5))

In [12]:
x[0][0]

np.int64(5)

In [13]:
x[0][1]

np.int64(10)

In [39]:
x[0][2]

np.int64(15)

In [45]:
int(str(len(x[0])-1))-1

4

In [ ]:
lst=[]
lst2=[]
for i in range(0,int(str(len(x[0]))),1):
    if x[1][i]>1:
        lst.append(x[0][i])
    else:
        lst2.append(x[0][i])

type(x)
print(lst2[1])


numpy.lib._arraysetops_impl.UniqueCountsResult

In [21]:
lst2

[np.int64(5), np.int64(10), np.int64(15), np.int64(30)]

In [22]:
print(lst2[1])

10
