In [2]:
import numpy as np

In [7]:
var=np.array([1,2,3,4,5,6,7,8,9])
print(np.sum(var))

45


In [8]:
b=var.reshape(3,3)
print(np.sum(b))

45


In [9]:
c=b.reshape(1,3,3)
print(np.sum(c))

45


In [10]:
var=np.array([1,2,3])
print(np.min(var))

1


In [11]:
var=np.array([1,2,3])
print(np.max(var))

3


In [12]:
var=np.array([1,2,2,2,2,3,3,3,3])
print(np.mean(var))

2.3333333333333335


In [ ]:
ages=np.array([[17,34,65,23,72,18,45,12,25,11],
              [22,42,16,46,38,12,62,54,15,18]])



In [18]:
# Find out the ages greater than 60
ages[ages> 18]

array([34, 65, 23, 72, 45, 25, 22, 42, 46, 38, 62, 54])

In [20]:
# Logical operator
# And(&)
# OR(|)
# NOT(~)



In [26]:
ages[(ages> 18) & (ages< 60)]

array([34, 23, 45, 25, 22, 42, 46, 38, 54])

In [28]:
ages[(ages%5==0) | (ages%7==0)]

array([65, 45, 25, 42, 15])

In [ ]:
ages[(ages>18) | (ages>60)]  

array([34, 65, 23, 72, 45, 25, 22, 42, 46, 38, 62, 54])

In [32]:
# np.where(condition,True,False)

# IT is also known as ternary operator



In [33]:
i=np.identity(4)
i

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [35]:
np.where(i==1,'hi1',False)

array([['hi1', 'False', 'False', 'False'],
       ['False', 'hi1', 'False', 'False'],
       ['False', 'False', 'hi1', 'False'],
       ['False', 'False', 'False', 'hi1']], dtype='<U5')

In [ ]:
# Replace the value with 0 which are greater than 20
# and remaining keep as it is.

In [39]:
np.where(b>20,0,b)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
# Replace the values with 0 which are divisible by 5.
# Remaining keep as it is.

np.where(c%5==0,0,c)

array([[[1, 2, 3],
        [4, 0, 6],
        [7, 8, 9]]])

In [42]:
import pandas as pd
# Series
# Dataframe

In [ ]:
#Difference between series and array.
# 1) Arrays belongs to numpy and series belongs to pandas.
# 2) String-> Objects  and in pandas complex-> Objects.
# 3) IT DISPLAYS only the data an in pandas It displays data,index,datatypes.
# 4) np.array(collectionsi) and in pandas pd.Series(collection)

