In [2]:
import numpy as np

In [7]:
var=np.arange(11,55,1)

In [8]:
var

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44,
       45, 46, 47, 48, 49, 50, 51, 52, 53, 54])

In [22]:
l=np.array([1,2,3,4,5])

var=l.shape
var

(5,)

In [10]:
a=np.arange(1,25)

In [11]:
b=a.reshape(6,4)

In [16]:
c=a.reshape(2,3,4)

In [19]:
a.shape


(24,)

In [20]:
b.shape

(6, 4)

In [21]:
c.shape

(2, 3, 4)

In [24]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [25]:
np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [27]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [28]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [29]:
np.zeros((2,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [30]:
np.identity(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [31]:
np.eye(9)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [32]:
np.random.randint(1,20,10)

array([10, 17, 14,  9,  9, 13,  4,  4, 16,  5], dtype=int32)

In [33]:
np.random.rand(10)

array([0.66743941, 0.83526905, 0.94804622, 0.96079726, 0.55003407,
       0.39108226, 0.30357754, 0.2398056 , 0.49983003, 0.35484148])

In [34]:
np.random.randn(10)

array([ 1.4359189 , -1.24713279, -0.07771198, -0.58277832, -0.48705399,
        1.80284074, -0.42578827, -0.46328515,  1.0792696 ,  1.18019082])

In [39]:
np.full((2,4,3),"😊")

array([[['😊', '😊', '😊'],
        ['😊', '😊', '😊'],
        ['😊', '😊', '😊'],
        ['😊', '😊', '😊']],

       [['😊', '😊', '😊'],
        ['😊', '😊', '😊'],
        ['😊', '😊', '😊'],
        ['😊', '😊', '😊']]], dtype='<U1')

In [49]:
a=np.arange(1,25)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [41]:
b=a.reshape(6,4)

In [56]:
c=a.reshape(3,2,4)
c

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]],

       [[17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [43]:
a[2]

np.int64(3)

In [54]:
a[5::-1]

array([6, 5, 4, 3, 2, 1])

In [59]:
c[2][0][1:3:1]

array([18, 19])

In [10]:
var=np.ones((2,4,2))

In [11]:
var

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])