In [2]:
import numpy as np



In [ ]:
# to check the version of numpy
np.__version__

'2.4.6'

In [3]:
#syntax to create array
# var=np.array(collection)

In [6]:
l=[1,3,5,7,9]
type(l)



list

In [7]:
a=np.array(l)
type(a)

numpy.ndarray

In [ ]:
b=np.array([True,False,True,False,True])
b

array([ True, False,  True, False,  True])

In [9]:
type(b[1])

numpy.bool

In [ ]:
c=np.array([True,False,1,True])
# c

array([1, 0, 1, 1])

In [12]:
type(c[1])

numpy.int64

In [16]:
c=np.array([True,False,1,True,3.4])
type(c[0])

numpy.float64

In [20]:
list1=[1,2,3,4,5]
list2=[6,7,8,9,10]

arr1=np.array(list1)
arr2=np.array(list2)

# arr1+arr2

arr1-arr2

array([-5, -5, -5, -5, -5])

In [22]:
n=np.array([1,2,3,4,5])
n.ndim

1

In [ ]:
n=np.array([[1,2,3],
            [2,3,4]])
n.ndim
n

array([[1, 2, 3],
       [2, 3, 4]])

In [ ]:
n=np.array([[[1,2,3],[2,3,4]],
            [[6,7,8],[8,9,10]]])

n

n.ndim

3

In [30]:
x=np.arange(1,11,2)
x

array([1, 3, 5, 7, 9])

In [3]:
var=np.arange(1,25)
type(var)

numpy.ndarray

In [33]:
# var.reshape(rows,columns)
# IT will convert 1d array into 2d array

In [ ]:
x=var.reshape(4,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [35]:
x.ndim

1

In [37]:
# var.reshape(rows,columns,depth):
# it will convert 1d array into 3d array

In [43]:
x=np.arange(1,25)

y=x.reshape(3,2,4)

y

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]],

       [[17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [45]:
x=np.arange(1,41)
y=x.reshape(2,5,4)
y

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16],
        [17, 18, 19, 20]],

       [[21, 22, 23, 24],
        [25, 26, 27, 28],
        [29, 30, 31, 32],
        [33, 34, 35, 36],
        [37, 38, 39, 40]]])